author: "Jan Valo\u0161ek, Sandrine B\xE9dard, Milo\u0161 Ke\u0159kovsk\xFD, Tom\xE1\
  \u0161 Rohan, Julien Cohen-Adad"
bibtex_bibfiles:
- ../paper.bib
execute:
  cache: ''
  exclude_patterns: []
  execute_notebooks: auto
  timeout: -1
html:
  baseurl: ''
  extra_footer: ''
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  favicon: ''
  google_analytics_id: ''
  home_page_in_navbar: true
  use_edit_page_button: false
  use_issues_button: false
  use_repository_button: false
html_theme_options:
  logo:
    image_dark: neurolibre-logo.png
    image_light: neurolibre-logo.png
launch_buttons:
  binderhub_url: https://binder-mcgill.conp.cloud
  notebook_interface: jupyterlab
  thebe: false
only_build_toc_files: true
repository:
  branch: main
  path_to_book: content
  url: https://github.com/roboneurolibre/PAM50-normalized-metrics-paper
sphinx:
  config:
    bibtex_default_style: plain
    bibtex_reference_style: author_year
    bibtex_tooltips: true
    html_css_files:
    - custom.css
    html_static_path:
    - _static
  local_extensions: null
  recursive_update: false
title: A database of the healthy human spinal cord morphometry in the PAM50 template
  space
